site_name: Arista ATD v3.0
site_url: https://hazardsg.github.io/atd-mkdocs-labguides
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en

  plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

# Page tree
nav:
  - Home: index.md
  - EOS Configuration:
    - Connecting: eos_configuration/connecting.md
    - Layer 2 Leaf-Spine: eos_configuration/l2ls.md
    - Layer 3 Leaf-Spine: eos_configuration/l3ls.md
    - VxLAN: eos_configuration/vxlan.md
    - L2 EVPN Services: eos_configuration/l2evpn.md
  - CloudVision Portal:
    - CVP Configlet, Change Control, and Rollback: cloudvision_portal/cvp_configlet.md
  - Programmability:
    - Connecting to your lab machine: programmability/programmability_connecting.md
  - Broadcaster Training:
    - Media Intro to IP Lab: broadcaster_training/media_ip_intro.md
  - Troubleshooting Training:
    - Troubleshooting Introduction: troubleshoot_training/tshoot_intro.md
  - Arista Graduate:
    - CloudVision Initial Configuration: arista_graduate/ag_initial_configuration.md